### PR TITLE
User host-masking & friends

### PR DESCRIPTION
**Pull request by kobishmueli**
1. User host-masking support.
2. whois module hook
3. version.c.SH updates

-Kobi.

### CODE REVIEW

**Comment by epiphani** [comment]
Sorry for the delay - somehow I didn't get any notifications on this.  Will have reviewed in a few days.

**Comment by epiphani** [comment]
A few preliminary comments:
- use of the USER_HOSTMASK define is inconsistent and would likely not compile with it undefined.  I see at least one place where User->mhost is referenced outside of ifdefs
- if we don't want people enabling this on the main network, we should undef by default for now
- the whois chook seems unrelated to this patch - do we need it in here?
- can you expand on what uhm_type and the chook idea?  is the plan to carve the masking algorithm into a fully pluggable implementation?

**Comment by kobishmueli** [comment]
@epiphani - sorry for the delay (xPsycho pointed me to this comment yesterday), my answers:
1. USER_HOSTMASK define is inconsistent - will review and fix.
2. This is correct, "Added module hook for WHOIS." and "Updated version.c.SH (Kobi --> Kobi_S & added RuneB)." are not related to the user host-masking. I just sent all the patches I had (I tried to make as many patches as I can per our previous discussions about "long" patches).
3. The idea is to add a masking algorithm that can be changed on the fly. If we'll want to change the algorithm at one point or another, we'll need to support at least two algorithm types to make the network consistent. The process will be something like:
A. Upgrade all servers.
B. Activate UHM type 1 once all servers are upgraded.
C. Create a new algorithm (type 2).
D. Upgrade all servers.
E. Activate UHM type 2 once all servers are upgraded.
F. Goto C (just with another type number)

-Kobi.

**Comment by eaescob** [comment]
@kobishmueli Where are we with this?

**Comment by kobishmueli** [comment]
@eaescob: per our online conversation, I've created another pull request (#31) and I'm closing this one.

-Kobi.

**Pull request closed without merging**
