### PR TITLE
Add services join requests.

### PR DESCRIPTION
**Pull request by kobishmueli**
This is the pull request for #42.

This feature is disabled by default, however, when enabled (either for cmode +r channels or for all channels), servers will send join requests to services via the SJR command.

Once approved, services will send a join approval with the AJ command.
Alternatively, if the join request is denied, services will send the relevant error message to the user.

(Note that I didn't include the command to enable this feature, I'll include it in the next pull request)

-Kobi.

### CODE REVIEW

**Comment by eaescob** [comment]
Should we hold off on merging this until the entire thing is ready for review?

**Comment by kobishmueli** [comment]
Yes, see #42, in anyway, we can do the release without including the services join requests and maybe add it at a later release.

Kobi.

**Comment by kobishmueli** [comment]
@eaescob: Per #42, I have changed it to use a new extended channel flag and I believe this should be included in the next release.

Kobi.

**Comment by eaescob** [comment]
Can you please fix the conflicts?

**Pull request merged**
